//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JSTest.Test {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ScriptResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ScriptResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JSTest.Test.ScriptResources", typeof(ScriptResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to assert.isTrue(true);.
        /// </summary>
        internal static string JsAssertSampleTest {
            get {
                return ResourceManager.GetString("JsAssertSampleTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to return JsHamcrest.Matchers.equalTo(&apos;10&apos;).matches(10) &amp;&amp;
        ///       JsHamcrest.Matchers.between(5).and(10).matches(7) &amp;&amp;
        ///       JsHamcrest.Matchers.greaterThan(Math.PI).matches(4);.
        /// </summary>
        internal static string JsHamcrestSampleTest {
            get {
                return ResourceManager.GetString("JsHamcrestSampleTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to var mockedObject = JsMockito.mock(Array);
        ///
        ///mockedObject.push(&apos;one&apos;);
        ///
        ///JsMockito.verify(mockedObject).push(&apos;one&apos;);.
        /// </summary>
        internal static string JsMockitoSampleTest {
            get {
                return ResourceManager.GetString("JsMockitoSampleTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to var mockControl = new MockControl();
        ///workerMock = mockControl.createMock(Worker);
        ///
        ///workerMock.expects().isFinished().andReturn(true);
        ///workerMock.expects().getValue().andReturn(&apos;hello&apos;);
        ///
        ///var result = doWork(workerMock);
        ///
        ///mockControl.verify();.
        /// </summary>
        internal static string JsMockSampleTest {
            get {
                return ResourceManager.GetString("JsMockSampleTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to function Worker() {
        ///  this.getValue = function () { /* ... */ };
        ///  this.isFinished = function () { /* ... */ };
        ///}
        ///
        ///function doWork(worker) {
        ///  if (worker.isFinished()) {
        ///    return worker.getValue();
        ///  }
        ///  else {
        ///    return null;
        ///  }
        ///}.
        /// </summary>
        internal static string JsMockSampleTestScriptBlock {
            get {
                return ResourceManager.GetString("JsMockSampleTestScriptBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;script language=&apos;JavaScript&apos;&gt;
        ///{0}
        ///&lt;/script&gt;.
        /// </summary>
        internal static string ScriptBlockFormat {
            get {
                return ResourceManager.GetString("ScriptBlockFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;script language=&apos;JavaScript&apos; src=&apos;{0}&apos;&gt;&lt;/script&gt;.
        /// </summary>
        internal static string ScriptIncludeFormat {
            get {
                return ResourceManager.GetString("ScriptIncludeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;script language=&apos;JavaScript&apos;&gt;
        ///(function () {{
        ///  try {{
        ///    WScript.Echo(JSON.stringify((function () {{
        ///      // START TEST BLOCK //
        ///{0}
        ///{1}
        ///{2}
        ///      // END TEST BLOCK //
        ///      return null;
        ///    }})()));
        ///    WScript.Quit(0);
        ///  }}
        ///  catch (ex) {{
        ///    WScript.Echo(JSON.stringify(ex));
        ///    WScript.Quit(1);
        ///  }}
        ///}})();
        ///&lt;/script&gt;.
        /// </summary>
        internal static string TestExecutorScriptBlockFormat {
            get {
                return ResourceManager.GetString("TestExecutorScriptBlockFormat", resourceCulture);
            }
        }
    }
}
